services:
  nginx:
    image: nginxinc/nginx-unprivileged:stable-alpine
    read_only: true
    user: nginx
    depends_on:
      - php
    ports:
      - '8080:8080'
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './public/:/app/public/:ro'
      - '/tmp'

  php:
    build:
      context: ./
      target: development
    working_dir: /app/
    user: www-data
    volumes:
      - './:/app/'