apiVersion: v1
kind: ConfigMap
metadata:
  name: symfony-demo-app
  namespace: main
  labels:
    app.kubernetes.io/name: symfony-demo-app
data:
  default.conf: |
    server {
      server_name symfony-demo;
      root /app/public;
      listen 8080;
      server_tokens off;
  
      location / {
          try_files $uri /index.php$is_args$args;
      }
  
      location ~ ^/index\.php(/|$) {
          fastcgi_pass localhost:9000;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT $document_root;
          internal;
      }
  
      location ~ \.php$ {
          return 404;
      }
  
      error_log stderr warn;
      access_log /dev/stdout main;
    }
